const shared=globalThis.InputBridge;const $=selector=>document.querySelector(selector);let settings=shared.mergeSettings();let saveTimer;
const PALETTES={flux:{accent:"#8b5cf6",accent2:"#22d3ee",background:"#080b14",surface:"#111827",text:"#f8fafc",muted:"#94a3b8"},ocean:{accent:"#0ea5e9",accent2:"#34d399",background:"#06131d",surface:"#0b2634",text:"#ecfeff",muted:"#82aeb8"},ember:{accent:"#f43f5e",accent2:"#f59e0b",background:"#14090b",surface:"#281216",text:"#fff7ed",muted:"#b99a91"},mono:{accent:"#e5e7eb",accent2:"#94a3b8",background:"#090a0c",surface:"#181a1f",text:"#f8fafc",muted:"#8a8f9c"}};
function saved(){const toast=$("#saveToast");toast.classList.add("show");clearTimeout(saved.timer);saved.timer=setTimeout(()=>toast.classList.remove("show"),800)}
function save(){clearTimeout(saveTimer);saveTimer=setTimeout(()=>chrome.storage.sync.set({settings},saved),80)}
function activeProfileId(){return settings.presetMode==="auto"?"auto":settings.manualPreset}
function description(id){if(id==="auto")return "Guesses from the game title and falls back to Default.";if(id==="custom")return "Your completely adjustable keyboard and mouse layout.";return shared.PRESETS[id]?.description||""}

function showTab(id){document.querySelectorAll("[data-tab]").forEach(button=>button.classList.toggle("active",button.dataset.tab===id));document.querySelectorAll("[data-panel]").forEach(panel=>panel.classList.toggle("active",panel.dataset.panel===id));chrome.storage.local.set({lastTab:id})}
document.querySelectorAll("[data-tab]").forEach(button=>button.addEventListener("click",()=>showTab(button.dataset.tab)));chrome.storage.local.get("lastTab",result=>showTab(result.lastTab||"home"));

function renderProfiles(){const root=$("#profileGrid");root.textContent="";const entries=[["auto",{name:"Auto-detect",icon:"✦",description:"Guess a profile from the visible game title."}],...Object.entries(shared.PRESETS),["custom",{name:"Custom",icon:"⌁",description:"Your own editable input layout."}]];for(const[id,item]of entries){const button=document.createElement("button");button.className=`profile-card${activeProfileId()===id?" active":""}`;button.innerHTML=`<span class="check">✓</span><span class="profile-icon">${item.icon}</span><strong>${item.name}</strong><p>${item.description}</p>`;button.addEventListener("click",()=>selectProfile(id));root.append(button)}}
function selectProfile(id){if(id==="auto"){settings.presetMode="auto";settings.autoDetect=true}else{settings.presetMode="manual";settings.manualPreset=id;if(shared.PRESETS[id])settings.mouseLook=shared.PRESETS[id].mouseLook}render();save()}

function renderBindings(){const root=$("#bindingGroups");root.textContent="";for(const[group,actions]of shared.ACTIONS){const card=document.createElement("div");card.className="binding-group";card.innerHTML=`<h3>${group}</h3>`;for(const[action,label]of actions){const row=document.createElement("div");row.className="binding-row";const text=document.createElement("span");text.textContent=label;const button=document.createElement("button");button.className="key-button";button.textContent=shared.keyLabel(settings.customBindings[action]);button.addEventListener("click",()=>captureBinding(button,action));row.append(text,button);card.append(row)}root.append(card)}}
function assignBinding(action,code){for(const name of Object.keys(settings.customBindings))if(code&&settings.customBindings[name]===code)settings.customBindings[name]="";settings.customBindings[action]=code;settings.presetMode="manual";settings.manualPreset="custom";render();save()}
function captureBinding(button,action){document.querySelectorAll(".key-button.listening").forEach(item=>item.classList.remove("listening"));button.classList.add("listening");button.textContent="Press input…";const cleanup=()=>{removeEventListener("keydown",onKey,true);removeEventListener("mousedown",onMouse,true)};const cancel=()=>{cleanup();renderBindings()};const onKey=event=>{event.preventDefault();event.stopPropagation();if(event.code==="Escape")return cancel();cleanup();assignBinding(action,event.code==="Backspace"?"":event.code)};const onMouse=event=>{event.preventDefault();event.stopPropagation();cleanup();assignBinding(action,`Mouse${event.button}`)};addEventListener("keydown",onKey,true);setTimeout(()=>addEventListener("mousedown",onMouse,true),0)}

function safeColor(value,fallback){return /^#[0-9a-f]{6}$/i.test(value||"")?value:fallback}
function updatePreview(){const theme=settings.theme;const preview=$("#themePreview");preview.style.setProperty("--preview-accent",theme.accent);preview.style.setProperty("--preview-accent2",theme.accent2);preview.style.setProperty("--preview-bg",theme.background);preview.style.setProperty("--preview-text",theme.text);preview.style.setProperty("--preview-muted",theme.muted);preview.style.setProperty("--preview-radius",`${theme.radius}px`);preview.style.setProperty("--preview-glow",`${Math.round(theme.glow/2)}px`);document.querySelectorAll("[data-theme]").forEach(button=>button.classList.toggle("active",button.dataset.theme===settings.themeStyle))}
function render(){for(const id of["accent","accent2","background","surface","text","muted"])settings.theme[id]=safeColor(settings.theme[id],shared.DEFAULT_SETTINGS.theme[id]);$("#enabled").checked=settings.enabled;$("#preset").value=activeProfileId();$("#presetDescription").textContent=description(activeProfileId());$("#showConnectionNotice").checked=settings.showConnectionNotice;$("#mouseLook").checked=settings.mouseLook;$("#mouseSensitivity").value=settings.mouseSensitivity;$("#mouseSensitivityValue").textContent=`${Number(settings.mouseSensitivity).toFixed(1)}×`;$("#invertMouseY").checked=settings.invertMouseY;$("#themeEnabled").checked=settings.themeEnabled;$("#themeIntensity").value=settings.themeIntensity;for(const id of["accent","accent2","background","surface","text","muted"])$("#"+id).value=settings.theme[id];$("#radius").value=settings.theme.radius;$("#radiusValue").textContent=`${settings.theme.radius}px`;$("#glow").value=settings.theme.glow;$("#glowValue").textContent=`${settings.theme.glow}%`;$("#axisRampMs").value=settings.axisRampMs;$("#axisRampValue").textContent=settings.axisRampMs?`${settings.axisRampMs}ms`:"Off";$("#gamepadPlacement").value=settings.developer.gamepadPlacement;$("#debugOverlay").checked=settings.developer.debugOverlay;$("#consoleLogs").checked=settings.developer.consoleLogs;renderProfiles();renderBindings();updatePreview()}

function bindBoolean(id,apply){$("#"+id).addEventListener("change",event=>{apply(event.target.checked);save()})}
bindBoolean("enabled",value=>settings.enabled=value);bindBoolean("showConnectionNotice",value=>settings.showConnectionNotice=value);bindBoolean("mouseLook",value=>settings.mouseLook=value);bindBoolean("invertMouseY",value=>settings.invertMouseY=value);bindBoolean("themeEnabled",value=>settings.themeEnabled=value);bindBoolean("debugOverlay",value=>settings.developer.debugOverlay=value);bindBoolean("consoleLogs",value=>settings.developer.consoleLogs=value);
$("#preset").addEventListener("change",event=>selectProfile(event.target.value));$("#mouseSensitivity").addEventListener("input",event=>{settings.mouseSensitivity=Number(event.target.value);$("#mouseSensitivityValue").textContent=`${settings.mouseSensitivity.toFixed(1)}×`;save()});$("#axisRampMs").addEventListener("input",event=>{settings.axisRampMs=Number(event.target.value);$("#axisRampValue").textContent=settings.axisRampMs?`${settings.axisRampMs}ms`:"Off";save()});$("#themeIntensity").addEventListener("change",event=>{settings.themeIntensity=event.target.value;save()});$("#gamepadPlacement").addEventListener("change",event=>{settings.developer.gamepadPlacement=event.target.value;save()});
for(const id of["accent","accent2","background","surface","text","muted"])$("#"+id).addEventListener("input",event=>{settings.theme[id]=event.target.value;settings.themeStyle="custom";updatePreview();save()});$("#radius").addEventListener("input",event=>{settings.theme.radius=Number(event.target.value);$("#radiusValue").textContent=`${settings.theme.radius}px`;updatePreview();save()});$("#glow").addEventListener("input",event=>{settings.theme.glow=Number(event.target.value);$("#glowValue").textContent=`${settings.theme.glow}%`;updatePreview();save()});
document.querySelectorAll("[data-theme]").forEach(button=>button.addEventListener("click",()=>{settings.themeStyle=button.dataset.theme;settings.theme={...settings.theme,...PALETTES[button.dataset.theme]};render();save()}));for(const[id,preset]of Object.entries(shared.PRESETS)){const option=document.createElement("option");option.value=id;option.textContent=preset.name;$("#copySource").append(option)}$("#copyProfile").addEventListener("click",()=>{const preset=shared.PRESETS[$("#copySource").value]||shared.PRESETS.default;settings.customBindings={...preset.bindings};settings.mouseLook=preset.mouseLook;settings.presetMode="manual";settings.manualPreset="custom";render();save()});
$("#exportSettings").addEventListener("click",()=>{const blob=new Blob([JSON.stringify({product:"InputBridge",version:1,settings},null,2)],{type:"application/json"});const url=URL.createObjectURL(blob);const anchor=document.createElement("a");anchor.href=url;anchor.download="inputbridge-settings.json";anchor.click();setTimeout(()=>URL.revokeObjectURL(url),1000)});$("#importSettings").addEventListener("change",async event=>{const file=event.target.files[0];if(!file)return;try{const parsed=JSON.parse(await file.text());settings=shared.mergeSettings(parsed.settings||parsed);render();save()}catch{alert("That file is not a valid InputBridge settings export.")}event.target.value=""});$("#restoreDefaults").addEventListener("click",()=>{if(!confirm("Restore every InputBridge setting and binding to its default?"))return;settings=shared.mergeSettings(shared.DEFAULT_SETTINGS);render();save()});
chrome.storage.local.get("runtimeStatus",result=>{const status=result.runtimeStatus;if(!status)return;const recent=Date.now()-status.updatedAt<30000;$(".pulse").classList.toggle("live",recent&&status.enabled);$("#statusLabel").textContent=recent?(status.enabled?"Connected":"InputBridge paused"):"Last detected session";$("#gameTitle").textContent=status.gameTitle||"Xbox Cloud Gaming";$("#statusProfile").textContent=status.presetName||"Default"});chrome.storage.sync.get({settings:shared.DEFAULT_SETTINGS},result=>{settings=shared.mergeSettings(result.settings);render()});
